---
apiVersion: machine.openshift.io/v1beta1
kind: MachineSet
metadata:
  annotations:
    # if instance type is unknown, so the autoscaler must be told about capacity:  https://access.redhat.com/solutions/6640721
    machine.openshift.io/GPU: "0"
    machine.openshift.io/memoryMb: "32768"
    machine.openshift.io/vCPU: "16"
  labels:
    machine.openshift.io/cluster-api-cluster: build03-vqlvf
  name: build03-vqlvf-ci-builds-worker-us-east-1a
  namespace: openshift-machine-api
spec:
  selector:
    matchLabels:
      machine.openshift.io/cluster-api-cluster: build03-vqlvf
      machine.openshift.io/cluster-api-machineset: build03-vqlvf-ci-builds-worker-us-east-1a
  template:
    metadata:
      annotations:
        # By the time we delete a machine, there should be nothing we care about.
        # The only times this is violated is pods in weird states. Ignore them.
        # https://github.com/openshift/machine-api-operator/blob/master/FAQ.md#i-want-to-skip-draining-when-i-delete-a-machine
        machine.openshift.io/exclude-node-draining: "true"
      labels:
        machine.openshift.io/cluster-api-cluster: build03-vqlvf
        machine.openshift.io/cluster-api-machine-role: worker
        machine.openshift.io/cluster-api-machine-type: worker
        machine.openshift.io/cluster-api-machineset: build03-vqlvf-ci-builds-worker-us-east-1a
    spec:
      metadata:
        labels:
          ci-workload: builds
      providerSpec:
        value:
          ami:
            id: ami-0b35795bcab04ee70
          apiVersion: awsproviderconfig.openshift.io/v1beta1
          blockDevices:
          - ebs:
              iops: 5000
              volumeSize: 2000
              volumeType: io1
          credentialsSecret:
            name: aws-cloud-credentials
          deviceIndex: 0
          iamInstanceProfile:
            id: build03-vqlvf-worker-profile
          instanceType: c5a.4xlarge
          kind: AWSMachineProviderConfig
          metadata: {}
          placement:
            availabilityZone: us-east-1a
            region: us-east-1
          securityGroups:
          - filters:
            - name: tag:Name
              values:
              - build03-vqlvf-worker-sg
          subnet:
            filters:
            - name: tag:Name
              values:
              - build03-vqlvf-private-us-east-1a
          tags:
          - name: kubernetes.io/cluster/build03-vqlvf
            value: owned
          userDataSecret:
            name: worker-user-data
      taints:
      - effect: NoSchedule
        key: node-role.kubernetes.io/ci-builds-worker
        value: ci-builds-worker
---
apiVersion: autoscaling.openshift.io/v1beta1
kind: MachineAutoscaler
metadata:
  name: build03-vqlvf-ci-builds-worker-us-east-1a
  namespace: openshift-machine-api
spec:
  maxReplicas: 120
  minReplicas: 0
  scaleTargetRef:
    apiVersion: machine.openshift.io/v1beta1
    kind: MachineSet
    name: build03-vqlvf-ci-builds-worker-us-east-1a