---
apiVersion: v1
kind: Namespace
metadata:
  name: ci-scheduling-webhook
---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: ci-scheduler-priority-builds
preemptionPolicy: PreemptLowerPriority
value: 1000
---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: ci-scheduler-priority-tests
preemptionPolicy: PreemptLowerPriority
value: 1000
---
apiVersion: node.k8s.io/v1
kind: RuntimeClass
metadata:
  name: ci-scheduler-runtime-builds
handler: runc
overhead:
  podFixed:
    # Reserve an additional 500m for each build on crio as overhead for the runtime
    memory: "500Mi"
    cpu: "500m"
scheduling:
  nodeSelector:
    ci-workload: builds
  tolerations:
    - effect: NoSchedule
      key: node-role.kubernetes.io/ci-builds-worker
      operator: Exists
    # legacy name
    - effect: NoSchedule
      key: node-role.kubernetes.io/ci-build-worker
      operator: Exists
---
apiVersion: node.k8s.io/v1
kind: RuntimeClass
metadata:
  name: ci-scheduler-runtime-tests
handler: runc
scheduling:
  nodeSelector:
    ci-workload: tests
  tolerations:
    - effect: NoSchedule
      key: node-role.kubernetes.io/ci-tests-worker
      operator: Exists
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: "ci-scheduling.ci.openshift.io"
  annotations:
    service.beta.openshift.io/inject-cabundle: "true"
webhooks:
  - name: "ci-schedulding.ci.openshift.io"
    rules:
      - apiGroups: [""]
        apiVersions: ["v1"]
        operations: ["CREATE"]
        resources: ["pods"]
        scope: "Namespaced"
    clientConfig:
      service:
        namespace: "ci"
        name: "ci-scheduling-admission-webhook"
        path: "/mutate/pods"
    admissionReviewVersions: ["v1"]
    reinvocationPolicy: "IfNeeded"
    sideEffects: None
    timeoutSeconds: 5
    failurePolicy: Ignore
---
apiVersion: v1
kind: Service
metadata:
  name: ci-scheduling-admission-webhook
  namespace: ci-scheduling-webhook
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: ci-scheduling-admission-webhook-serving-cert
spec:
  ports:
    - name: main
      port: 443
      protocol: TCP
      targetPort: 8443
  selector:
    app: ci-scheduling-admission-webhook
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ci-scheduling-admission-webhook
  name: ci-scheduling-admission-webhook
  namespace: ci-scheduling-webhook
spec:
  replicas: 4
  selector:
    matchLabels:
      app: ci-scheduling-admission-webhook
  template:
    metadata:
      labels:
        app: ci-scheduling-admission-webhook
    spec:
      containers:
        - image: quay.io/jupierce/ci-tainting-webhook:latest
          name: ci-scheduling-webhook
          imagePullPolicy: Always
          ports:
            - name: main
              containerPort: 8443
          volumeMounts:
            - name: serving-cert
              mountPath: /etc/pki/tls/certs/admission
              readOnly: true
          resources:
            requests:
              memory: "2Gi"
              cpu: "250m"
      volumes:
        - name: serving-cert
          secret:
            defaultMode: 420
            secretName: ci-scheduling-admission-webhook-serving-cert
