---
apiVersion: v1
kind: Namespace
metadata:
  name: ci-op-jmp
---
apiVersion: v1
kind: Pod
metadata:
  name: webhook-example-build-pod-busybox
  namespace: ci-op-jmp
  labels:
    openshift.io/build.name: webhook-example-build-pod-busybox
spec:
  containers:
  - name: busybox
    image: registry.access.redhat.com/ubi8
    command:
    - sleep
    - "30"
    resources:
      requests:
        cpu: "100m"
  terminationGracePeriodSeconds: 0
  restartPolicy: Never
